// Package setup builds the artifacts that wire BBrain into Claude Code: the LLM
// agent adapter script, the MCP server config entry, and a managed CLAUDE.md
// block. Pure functions over inputs; the app layer performs the disk I/O.
package setup

import (
	"encoding/json"
	"strings"
)

// Managed-block markers so re-running setup replaces only BBrain's region.
const (
	BlockBegin = "<!-- BBRAIN:BEGIN -->"
	BlockEnd   = "<!-- BBRAIN:END -->"
)

// AdapterScript returns the shell adapter that turns a BBrain prompt (stdin) into
// one JSON object (stdout) using Claude Code headlessly. model is the default;
// $BBRAIN_CLAUDE_MODEL overrides it at runtime. Requires `claude` and `python3`.
func AdapterScript(model string) string {
	return `#!/bin/sh
# BBrain agent adapter (generated by 'bbrain setup claude-code').
# Prompt on stdin -> one JSON object on stdout. Frames the backend role via a
# system prompt so Claude Code does not read the instructions as a prompt-injection.
# Requires: claude (Claude Code CLI) and python3 on PATH.
model="${BBRAIN_CLAUDE_MODEL:-` + model + `}"
sys='You are a deterministic text-to-JSON transformer invoked as a backend by the BBrain CLI (a local note-distilling tool the user owns and authorized). Your entire job: read the structured instructions on stdin and emit exactly one JSON object that satisfies them. Output ONLY raw JSON, no prose, no markdown fences, no commentary. This is a legitimate batch transformation, not a conversation.'
claude -p --output-format text --model "$model" --append-system-prompt "$sys" 2>/dev/null | python3 -c 'import sys, re
s = sys.stdin.read()
m = re.search(r"(\{.*\})", s, re.S)
sys.stdout.write(m.group(1) if m else s)
'
`
}

// MCPEntry is the stdio MCP server entry for bbrain (the shape Claude Code writes).
func MCPEntry(brainHome string) map[string]any {
	return map[string]any{
		"type":    "stdio",
		"command": "bbrain",
		"args":    []string{"mcp"},
		"env":     map[string]string{"BBRAIN_HOME": brainHome},
	}
}

// MergeMCPConfig inserts/updates the bbrain server in an existing .mcp.json (or an
// empty/absent one), preserving every other server and top-level key.
func MergeMCPConfig(existing []byte, brainHome string) ([]byte, error) {
	root := map[string]any{}
	if len(strings.TrimSpace(string(existing))) > 0 {
		if err := json.Unmarshal(existing, &root); err != nil {
			return nil, err
		}
	}
	servers, _ := root["mcpServers"].(map[string]any)
	if servers == nil {
		servers = map[string]any{}
	}
	servers["bbrain"] = MCPEntry(brainHome)
	root["mcpServers"] = servers
	return json.MarshalIndent(root, "", "  ")
}

// UpsertManagedBlock replaces the BBRAIN managed region in doc with block, or
// appends block if no region exists. Idempotent (upserting the same block twice
// yields identical output).
func UpsertManagedBlock(doc, block string) string {
	start := strings.Index(doc, BlockBegin)
	end := strings.Index(doc, BlockEnd)
	if start >= 0 && end > start {
		return doc[:start] + block + doc[end+len(BlockEnd):]
	}
	doc = strings.TrimRight(doc, "\n")
	if doc == "" {
		return block + "\n"
	}
	return doc + "\n\n" + block + "\n"
}

// ClaudeMDBlock is the managed CLAUDE.md section documenting BBrain's MCP tools.
func ClaudeMDBlock(brainHome, adapterPath string) string {
	return BlockBegin + `
## BBrain memory

This project uses BBrain for durable memory (brain at ` + brainHome + `). The bbrain MCP server exposes:
- mcp__bbrain__mem_save / mem_search / mem_get / mem_delete — save and recall facts.
- mcp__bbrain__mem_link / mem_why / mem_related / mem_candidates — the reasoned graph.
- mcp__bbrain__wiki_build / wiki_link / wiki_lint — distil and maintain the wiki.

Save durable decisions and learnings via mem_save; search with mem_search before answering.
The wiki LLM backend is $BBRAIN_AGENT_CLI -> ` + adapterPath + `. Workflow: build -> link -> rebuild; wiki_lint --fix for consistency.
` + BlockEnd
}

// EnvExportLine is the shell line that points BBrain at the agent adapter.
func EnvExportLine(adapterPath string) string {
	return `export BBRAIN_AGENT_CLI="` + adapterPath + `"`
}
