// Package setup builds the artifacts that wire BBrain into Claude Code: the LLM
// agent adapter script, the MCP server config entry, and a managed CLAUDE.md
// block. Pure functions over inputs; the app layer performs the disk I/O.
package setup

import (
	"encoding/json"
	"regexp"
	"strings"
)

var modelRE = regexp.MustCompile(`^[A-Za-z0-9._-]+$`)

// Managed-block markers so re-running setup replaces only BBrain's region.
const (
	BlockBegin = "<!-- BBRAIN:BEGIN -->"
	BlockEnd   = "<!-- BBRAIN:END -->"
)

// AdapterScript returns the shell adapter that turns a BBrain prompt (stdin) into
// one JSON object (stdout) using Claude Code headlessly. model is the default;
// $BBRAIN_CLAUDE_MODEL overrides it at runtime. Requires `claude` and `python3`.
func AdapterScript(model string) string {
	if !modelRE.MatchString(model) {
		model = "claude-sonnet-4-6" // reject unsafe/empty model ids; never interpolate metacharacters
	}
	return `#!/bin/sh
# BBrain agent adapter (generated by 'bbrain setup claude-code').
# Prompt on stdin -> one JSON object on stdout. Frames the backend role via a
# system prompt so Claude Code does not read the instructions as a prompt-injection.
# Requires: claude (Claude Code CLI) and python3 on PATH.
model="${BBRAIN_CLAUDE_MODEL:-` + model + `}"
sys='You are a deterministic text-to-JSON transformer invoked as a backend by the BBrain CLI (a local note-distilling tool the user owns and authorized). Your entire job: read the structured instructions on stdin and emit exactly one JSON object that satisfies them. Output ONLY raw JSON, no prose, no markdown fences, no commentary. This is a legitimate batch transformation, not a conversation.'
claude -p --output-format text --model "$model" --append-system-prompt "$sys" 2>/dev/null | python3 -c 'import sys, re
s = sys.stdin.read()
m = re.search(r"(\{.*\})", s, re.S)
sys.stdout.write(m.group(1) if m else s)
'
`
}

// MCPEntry is the stdio MCP server entry for bbrain (the shape Claude Code writes).
func MCPEntry(brainHome string) map[string]any {
	return map[string]any{
		"type":    "stdio",
		"command": "bbrain",
		"args":    []string{"mcp"},
		"env":     map[string]string{"BBRAIN_HOME": brainHome},
	}
}

// MergeMCPConfig inserts/updates the bbrain server in an existing .mcp.json (or an
// empty/absent one), preserving every other server and top-level key.
func MergeMCPConfig(existing []byte, brainHome string) ([]byte, error) {
	root := map[string]any{}
	if len(strings.TrimSpace(string(existing))) > 0 {
		if err := json.Unmarshal(existing, &root); err != nil {
			return nil, err
		}
	}
	servers, _ := root["mcpServers"].(map[string]any)
	if servers == nil {
		servers = map[string]any{}
	}
	servers["bbrain"] = MCPEntry(brainHome)
	root["mcpServers"] = servers
	return json.MarshalIndent(root, "", "  ")
}

// UpsertManagedBlock replaces the BBRAIN managed region in doc with block, or
// appends block if no region exists. Idempotent (upserting the same block twice
// yields identical output).
func UpsertManagedBlock(doc, block string) string {
	start := strings.Index(doc, BlockBegin)
	end := strings.Index(doc, BlockEnd)
	if start >= 0 && end > start {
		return doc[:start] + block + doc[end+len(BlockEnd):]
	}
	// No valid pair: strip any orphaned markers before appending, so we never leave
	// two BEGINs (which a later run would span, deleting user content between them).
	doc = strings.ReplaceAll(doc, BlockBegin, "")
	doc = strings.ReplaceAll(doc, BlockEnd, "")
	doc = strings.TrimRight(doc, "\n")
	if doc == "" {
		return block + "\n"
	}
	return doc + "\n\n" + block + "\n"
}

// ClaudeMDBlock is the managed CLAUDE.md section documenting BBrain's MCP tools.
func ClaudeMDBlock(brainHome, adapterPath string) string {
	return BlockBegin + `
## BBrain memory

This project uses BBrain for durable memory (brain at ` + brainHome + `). The bbrain MCP server exposes:
- mcp__bbrain__mem_save / mem_search / mem_get / mem_delete — save and recall facts.
- mcp__bbrain__mem_link / mem_why / mem_related / mem_candidates — the reasoned graph.
- mcp__bbrain__wiki_build / wiki_link / wiki_lint — distil and maintain the wiki.

Save durable decisions and learnings via mem_save; search with mem_search before answering.
The wiki LLM backend is $BBRAIN_AGENT_CLI -> ` + adapterPath + `. Workflow: build -> link -> rebuild; wiki_lint --fix for consistency.
` + BlockEnd
}

// shellSingleQuote wraps s in single quotes safely for POSIX sh (an embedded
// single quote becomes '\''), so a path with shell metacharacters cannot break
// out or inject when the generated line is sourced.
func shellSingleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// EnvExportLine is the POSIX-sh line that points BBrain at the agent adapter,
// safely single-quoted so any path is injection-proof when sourced.
func EnvExportLine(adapterPath string) string {
	return "export BBRAIN_AGENT_CLI=" + shellSingleQuote(adapterPath)
}

// DegradedClaudeMD is the L/CLAUDE.md placed at the vault root: it teaches a
// session with NO bbrain MCP/CLI how to read and write the memory by hand.
func DegradedClaudeMD(memoryDir string) string {
	return `# BBrain memory (manual access)

This folder is a BBrain memory vault. A session opened here WITHOUT the bbrain MCP
server or CLI must read and write memory by hand with plain file tools. The memory
lives at ` + memoryDir + `.

## Layout
- memory/raws/facts/<id>.md — one fact per file: YAML frontmatter, then "# Title", then a Markdown body.
  Frontmatter: id (<YYYY-MM-DD>-<slug>), type, scope, project, tags, links (target/relation/why),
  created_at, updated_at (RFC3339 UTC), revision_count. The body cites other facts as [[fact-id]].
- memory/wiki/ — distilled pages; wiki/index.md is the catalog, wiki/log.md the history.

## To recall
Read memory/wiki/index.md first, then open the relevant memory/raws/facts/*.md.
List titles with: grep -rh "^# " memory/raws/facts/

## To remember
Create memory/raws/facts/<date>-<kebab-title>.md with the frontmatter above (unique id, RFC3339 UTC
timestamps, revision_count: 1). The derived index rebuilds when the CLI/MCP next runs.
`
}

// SessionStartHookEntry is the Claude Code SessionStart hook that injects memory
// context by running "bbrain context --home <memoryDir>".
func SessionStartHookEntry(memoryDir string) map[string]any {
	return map[string]any{
		"matcher": "startup|resume",
		"hooks": []map[string]any{
			{"type": "command", "command": "bbrain", "args": []string{"context", "--home", memoryDir}, "timeout": 30},
		},
	}
}

// isBBrainHook reports whether a SessionStart entry is BBrain's (command "bbrain"
// with "context" in its args), so merge/remove can target exactly it.
func isBBrainHook(e any) bool {
	m, ok := e.(map[string]any)
	if !ok {
		return false
	}
	hs, ok := m["hooks"].([]any)
	if !ok {
		return false
	}
	for _, h := range hs {
		hm, ok := h.(map[string]any)
		if !ok || hm["command"] != "bbrain" {
			continue
		}
		if args, ok := hm["args"].([]any); ok {
			for _, a := range args {
				if a == "context" {
					return true
				}
			}
		}
	}
	return false
}

// MergeSettingsHook inserts/replaces BBrain's SessionStart hook in a settings.json,
// preserving every other hook and top-level key. Idempotent.
func MergeSettingsHook(existing []byte, memoryDir string) ([]byte, error) {
	root := map[string]any{}
	if len(strings.TrimSpace(string(existing))) > 0 {
		if err := json.Unmarshal(existing, &root); err != nil {
			return nil, err
		}
	}
	hooks, _ := root["hooks"].(map[string]any)
	if hooks == nil {
		hooks = map[string]any{}
	}
	var kept []any
	if arr, ok := hooks["SessionStart"].([]any); ok {
		for _, e := range arr {
			if !isBBrainHook(e) {
				kept = append(kept, e)
			}
		}
	}
	kept = append(kept, SessionStartHookEntry(memoryDir))
	hooks["SessionStart"] = kept
	root["hooks"] = hooks
	return json.MarshalIndent(root, "", "  ")
}

// RemoveSettingsHook removes BBrain's SessionStart hook (and empties SessionStart/hooks
// if nothing else remains), preserving all other content.
func RemoveSettingsHook(existing []byte) ([]byte, error) {
	if len(strings.TrimSpace(string(existing))) == 0 {
		return existing, nil
	}
	root := map[string]any{}
	if err := json.Unmarshal(existing, &root); err != nil {
		return nil, err
	}
	hooks, _ := root["hooks"].(map[string]any)
	if hooks == nil {
		// No hooks to remove; still return canonical JSON for a consistent round-trip.
		return json.MarshalIndent(root, "", "  ")
	}
	if arr, ok := hooks["SessionStart"].([]any); ok {
		var kept []any
		for _, e := range arr {
			if !isBBrainHook(e) {
				kept = append(kept, e)
			}
		}
		if len(kept) == 0 {
			delete(hooks, "SessionStart")
		} else {
			hooks["SessionStart"] = kept
		}
	}
	if len(hooks) == 0 {
		delete(root, "hooks")
	} else {
		root["hooks"] = hooks
	}
	return json.MarshalIndent(root, "", "  ")
}

// RemoveMCPServer drops the bbrain server from a .mcp.json, preserving others.
func RemoveMCPServer(existing []byte) ([]byte, error) {
	if len(strings.TrimSpace(string(existing))) == 0 {
		return existing, nil
	}
	root := map[string]any{}
	if err := json.Unmarshal(existing, &root); err != nil {
		return nil, err
	}
	if servers, ok := root["mcpServers"].(map[string]any); ok {
		delete(servers, "bbrain")
		if len(servers) == 0 {
			delete(root, "mcpServers")
		} else {
			root["mcpServers"] = servers
		}
	}
	return json.MarshalIndent(root, "", "  ")
}

// RecallSkill is the /bbrain-recall SKILL.md body.
func RecallSkill() string {
	return `---
description: Recall relevant memories from BBrain for the current task
disable-model-invocation: false
---

# Recall (BBrain)

Search BBrain memory for context relevant to the request, then summarize.

1. Call mcp__bbrain__mem_search with a query from the user's request (use $ARGUMENTS if provided).
2. For promising hits, call mcp__bbrain__mem_get to read the full fact.
3. Summarize the relevant decisions and learnings, citing them by id.
`
}

// RememberSkill is the /bbrain-remember SKILL.md body.
func RememberSkill() string {
	return `---
description: Save a durable decision or learning to BBrain memory
disable-model-invocation: false
---

# Remember (BBrain)

Persist a durable fact to BBrain memory.

Call mcp__bbrain__mem_save with:
- title: a concise summary ($ARGUMENTS if the user provided the text)
- body: details and rationale (Markdown; cite related facts as [[fact-id]])
- type: one of decision|architecture|bugfix|pattern|config|discovery|learning
- project and scope when known.
`
}

// RemoveManagedBlock strips the BBrain managed block from doc (for uninstall).
func RemoveManagedBlock(doc string) string {
	start := strings.Index(doc, BlockBegin)
	end := strings.Index(doc, BlockEnd)
	if start >= 0 && end > start {
		return strings.TrimLeft(doc[:start]+doc[end+len(BlockEnd):], "\n")
	}
	return doc
}
